### ISSUE TITLE
A short list of quirks, inconsistencies and edge cases :)

### ISSUE THREAD

**Issue by bobthecow** [minad/typohero#2]
I'm trying TypoHero on a relatively large site that's been using fast-aleck. I gave it a run through and generated a diff to see how many issues I could find. I'm happy to note that it's really solid with this data set. The following, however, could definitely be improved:

 * fast-aleck doesn't include trailing periods in caps spans: `<span class="caps">HOT</span>.`, but Typohero includes the period inside the span `<span class="caps">HOT.</span>`. This seems like an overeager attempt to include the periods of initialisms inside the span?

 * I don't have a copy of Elements of Typographic Style around, but if I recall correctly, strings of three or more initials should be treated differently. For example, fast-aleck requires three letters in a row before wrapping in `<span class="caps">`.

 * fast-aleck also wraps parts of words when there's a mixed caps word, like `No<span class="caps">SQL</span>`. I'm not as convinced that this is the correct way to do this, though :)

 * Typohero seems to miss some runs of caps, for example it got `HTML` but didn't pick up `XHTML` here: `<a href="/article/uberquick-comments-in-htmlxhtml/">Uberquick comments in <span class="caps">HTML</span>/XHTML</a>`.

 * Typohero inserts a hairspace around em dashes even when the dash isn't between words (and doesn't already have a space): `<p>— John Updike</p>` => `<p> — John Updike</p>`

 * It also changed `<p>foo<br>\n…</p>` into `<p>foo<br> …</p>`

 * Typohero completely misses runs of caps inside parenthesis or quotes: `foo (BAR) baz` and `“QUX”` don't get caps spans. This seems to be related to the reason `HTML` gets a span but `/XHTML` doesn't in `HTML/XHTML`.

 * Also, `Underscore delimited caps strings <span class="caps">ARE</span>_A_BIT_WEIRD` :)

 * It does do a better job with contractions, for what it's worth: `<span class="caps">DON’T</span>` (fast-aleck does `<span class="caps">DON</span>’T`).

 * The ampersand in `(& what)` doesn't get an `amp` span.

 * I haven't tested extensively, but it seems to be forgetting the `<span class="dquo">` on curley quotes at the start of `<h1>` tags some of the time — and maybe other headings?

Sorry about the list, I'm happy to split it up into individual issues if you want :)

**Comment by minad** [comment]
Cool thx, this is a very good list and these issues are also easy to fix i guess.

It would be great if you could create a pr with failing tests in the test suite. This would help me a lot to fix the issues quickly next week.

Am 28. März 2015 08:22:28 MEZ, schrieb Justin Hileman <notifications@github.com>:

**Comment by bobthecow** [comment]
I've added failing test cases in #4. They're incomplete, as I haven't been able to isolate all of 'em yet, and I'm not sure if all of them are valid. But there's a checklist, so feel free to look at the four that don't have test coverage, too :)

**Comment by minad** [comment]
Thx. I will take a look. Please note that I don't want to copy fastalecks behavior where it doesn't make sense like mixed case words for example.

But most of the points that you mentioned were valid.

Am 29. März 2015 20:17:21 MESZ, schrieb Justin Hileman <notifications@github.com>:

**Comment by bobthecow** [comment]
Agreed. Only copy where it makes sense. I included the `NoSQL` case because I wasn't sure if it made sense to do something like `<span class="caps">NoSQL</span>` for something that wasn't strictly caps, but almost? Or do `<span class="caps">N</span>o<span class="caps">SQL</span>`.

Prolly the best way to handle it is to ignore mixed case words entirely.

**Comment by minad** [comment]
Yes ignoring makes most sense here. If one really wants to have that, one should create another span with class mixed but I don't think this is necessary.

Am 30. März 2015 16:47:42 MESZ, schrieb Justin Hileman <notifications@github.com>:

**Comment by minad** [comment]
closed in favor of #4
